### ISSUE TITLE
Context menu not available in VSCodium

### ISSUE THREAD

**Issue by Muzosh** [mhutchie/vscode-git-graph#863]
**Describe the Bug**
I recently switched from VSCode to VSCodium. Git Graph is available in both extension registries, however the context menu in VSCodium doesn't work.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Install VSCodium
2. Install GitGraph from the default extension registry (however, I also tried installing from .vsix file and problem still persists
3. Open any git repo
4. Open git graph for that repo
5. Right click on any commit

Only `Cut`, `Copy` and `Paste` commands are available:
<img width="649" alt="image" src="https://github.com/user-attachments/assets/27f53c6e-6080-47a4-92b9-aafdac7224f9" />

**Expected Behaviour**
I would expect a list of options what to do with clicked commit. Screenshot from VSCode:
![image](https://github.com/user-attachments/assets/9e02c278-f140-4508-ae69-d4333fbd400a)

**Environment**
 - Git Graph Extension Version: 1.30.0 in both VSCode and VSCodium
 - Visual Studio Codium Version: 1.96.2
 - Operating System: MacOS Sequoia 15.2

**Comment by codeingforcoffee** [comment]
bump

**Comment by codeingforcoffee** [comment]
plz fix this issue ASAP！！！！

**Comment by stidch** [comment]
I'm in the exact same situation. I just switched from VSCode to VSCodium. Git Graph is available in both extension registries, however the context menu in VSCodium doesn't work.

Is there a workaround for this?

**Comment by ATGardner** [comment]
i am using vscode canary, and i am having the same issue as well. i assume this problem will soon arrive at the stable channel of vscode as well

vscode:
```
Version: 1.97.0-insider (Universal)
Commit: 69d97b0773575a75736850370918e1171cfde5c6
Date: 2025-01-13T09:58:56.423Z
Electron: 32.2.7
ElectronBuildId: 10660205
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0
```

**Comment by jraygauthier** [comment]
Potentially related, contrary to mouse right click, when I hit the "Menu Key" (or Shift+F10), I get the Cut/Copy/Paste menu instead of the full fledged contextual menu for the currently focused item.

**Comment by webberpuma** [comment]
Latest Vscode Insider has this issue as well

**Comment by RandalSchwartz** [comment]
Is there an older version of this extension that works?  Or is the problem inherently with vscode, and we're waiting for that to be fixed?

**Comment by nnmrts** [comment]
@RandalSchwartz It seems to be an upstream breaking change in vscode. This extension didn't update for quite some time.

EDIT: Someone should create an issue in the vscode repo, maybe they can assist us here.

**Comment by RandalSchwartz** [comment]
I don't know enough about extensions to even know what to report.  Can someone who is familiar with this extension and how it works please file an issue with vscode, and link it from here so I can comment and watch?

**Comment by nnmrts** [comment]
This issue is fixed in the latest insiders build and it seems to be landing in 1.97.2 as well. Thanks to all the issue reporters, pull requesters and fixers in this repository and the electron (https://github.com/electron/electron/issues/44976, https://github.com/electron/electron/pull/44978) and vscode (https://github.com/microsoft/vscode/issues/239862, https://github.com/microsoft/vscode/pull/240261) repos. @Muzosh, can you confirm and close?

**Comment by ismatjon** [comment]
@Muzosh vscode 1.97.2 is out and the issue has been fixed. Please, close the issue

**Comment by Muzosh** [comment]
Sorry I didn't have much time lately. Closing the issue based on @ismatjon 's witness

**Comment by stidch** [comment]
@ismatjon @Muzosh I have updated to `VSCodium 1.97.2` and the `Git Graph` extension is on version `1.30.0`, but the **Context Menu** is still showing only `Cut/Copy/Paste`.

Am I missing something?

![Image](https://github.com/user-attachments/assets/716caf81-e900-48a1-82cb-327d5dbcd40c)

![Image](https://github.com/user-attachments/assets/dad6a4d8-d783-4ed8-9356-29a0ba0e7662)

**Comment by ismatjon** [comment]
@stidch For some reason in vscodium the issue is still present, while it is fixed in vscode. Maybe vscodium is a bit slower in updates than vscode.

**Comment by Muzosh** [comment]
Reopening. Will close again once the issue is resolved in VSCodium
